"""The simulation clock is what stops the demo data going stale, so the tests
focus on the properties that make it safe to run unattended in the app: it only
ever writes whole hours, it is idempotent, and it never rewinds."""

import os
import sys
from datetime import datetime, timedelta

os.environ["DATABASE_URL"] = "sqlite:///./test_simulation.db"
os.environ["MONGODB_URL"] = ""
os.environ["REDIS_URL"] = ""

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest  # noqa: E402

from app.core.database import Base, SessionLocal, engine  # noqa: E402
from app.ml import features as feat  # noqa: E402
from app.models import ridership, schedule, station, train  # noqa: E402
from app.services import simulation as sim  # noqa: E402

STATIONS = [
    ("128", 11000),
    ("235", 14600),
    ("L08", 4200),
    ("A09", 7300),
]
NOW = datetime(2026, 9, 28, 14, 0, 0)


@pytest.fixture(autouse=True)
def fresh_db():
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    for i, (code, cap) in enumerate(STATIONS):
        db.add(station.Station(
            id=code, code=code, name=f"Stop {code}",
            line=["1/2/3", "A/C/E", "L", "A/C/E"][i], zone="Zone-1",
            lat=40.0, lng=-73.0, capacity_per_hour=cap,
        ))
    for line in ("1/2/3", "A/C/E", "L"):
        for n in range(1, 4):
            db.add(train.Train(
                id=feat.train_code(line, n), code=feat.train_code(line, n),
                model="R160", capacity=1248, status="active",
            ))
    db.commit()
    yield db
    db.close()


def test_hour_floor_truncates_to_the_bucket():
    assert sim.hour_floor(datetime(2026, 9, 28, 14, 37, 12, 5)) == NOW
    assert sim.hour_floor(NOW) == NOW


def test_jitter_is_deterministic_and_in_range():
    first = [sim.jitter(i, 100, 8, 1) for i in range(50)]
    second = [sim.jitter(i, 100, 8, 1) for i in range(50)]
    assert first == second
    assert all(0.0 <= v < 1.0 for v in first)
    # Different salt must not collapse onto the same draw.
    assert sim.jitter(3, 100, 8, 1) != sim.jitter(3, 100, 8, 2)


def test_day_index_is_absolute_not_window_relative():
    """The value for a given calendar day must not depend on the window the
    clock is currently operating in, or a backfill would disagree with the seed.

    Concretely: an hour generated today and the same hour of the same day
    generated by a backfill a month later must land on the same index.
    """
    day = datetime(2026, 9, 28, 14, 0, 0)
    assert sim.day_index(day) == sim.day_index(day + timedelta(hours=5))
    assert sim.day_index(day) == sim.day_index(day.replace(minute=59, second=59))
    assert sim.day_index(day) != sim.day_index(day + timedelta(days=1))


def test_ridership_rows_for_hour_covers_every_station():
    rows = sim.ridership_rows_for_hour(STATIONS, NOW)
    assert len(rows) == len(STATIONS)
    assert {r.station_id for r in rows} == {c for c, _ in STATIONS}


def test_ridership_row_ids_are_content_addressed():
    a = sim.ridership_rows_for_hour(STATIONS, NOW)
    b = sim.ridership_rows_for_hour(STATIONS, NOW)
    assert [r.id for r in a] == [r.id for r in b]


def test_ridership_peaks_morning_and_evening():
    """The regression the clock must not reintroduce: a flat, or hour-shifted,
    profile. 08:00 and 17:00 are the two curve peaks."""
    occupancies = []
    for hour in range(24):
        rows = sim.ridership_rows_for_hour(STATIONS, datetime(2026, 9, 28, hour, 0, 0))
        occupancies.append(sum(r.occupancy for r in rows))
    assert occupancies.index(max(occupancies)) in (8, 17)
    assert occupancies[3] < occupancies[8]
    assert occupancies[12] < occupancies[17]


def test_weekend_is_quieter_than_weekday():
    monday = sim.ridership_rows_for_hour(STATIONS, datetime(2026, 9, 28, 8, 0, 0))
    sunday = sim.ridership_rows_for_hour(STATIONS, datetime(2026, 10, 4, 8, 0, 0))
    assert sum(r.occupancy for r in sunday) < sum(r.occupancy for r in monday)


def test_schedule_headway_is_tighter_at_peak():
    peak = sim.schedule_rows_for_hour(["128", "235"], "TR-123-01", 0, datetime(2026, 9, 28, 8))
    off = sim.schedule_rows_for_hour(["128", "235"], "TR-123-01", 0, datetime(2026, 9, 28, 3))
    assert len(peak) == 15 and peak[0].headway_min == 4
    assert len(off) == 7 and off[0].headway_min == 8
    assert all(r.delay_min == 0 for r in off)


def test_schedule_rows_are_stable_for_the_same_hour():
    a = sim.schedule_rows_for_hour(["128", "235"], "TR-123-01", 0, datetime(2026, 9, 28, 8))
    b = sim.schedule_rows_for_hour(["128", "235"], "TR-123-01", 0, datetime(2026, 9, 28, 8))
    assert [r.id for r in a] == [r.id for r in b]


def test_schedule_delay_does_not_depend_on_insert_order():
    """A running insert counter used to drive the off-peak delay, so generating
    one hour on its own gave a different answer than generating it in a batch."""
    alone = sim.schedule_rows_for_hour(["128", "235"], "TR-123-01", 0, datetime(2026, 9, 28, 8))
    sim.schedule_rows_for_hour(["128", "235"], "TR-999-01", 0, datetime(2026, 9, 28, 8))
    after = sim.schedule_rows_for_hour(["128", "235"], "TR-123-01", 0, datetime(2026, 9, 28, 8))
    assert [r.delay_min for r in alone] == [r.delay_min for r in after]


def test_schedule_for_line_with_no_stations_is_empty():
    assert sim.schedule_rows_for_hour([], "TR-123-01", 0, NOW) == []


def test_advance_from_empty_writes_only_the_current_hour(fresh_db):
    result = sim.advance(fresh_db, now=NOW)
    assert result["ridership"] == len(STATIONS)
    assert result["hours"] == 1


def test_advance_is_a_noop_when_already_current(fresh_db):
    sim.advance(fresh_db, now=NOW)
    again = sim.advance(fresh_db, now=NOW)
    assert again == {"hours": 0, "ridership": 0, "schedules": 0, "pruned": 0}
    assert fresh_db.query(ridership.RidershipRecord).count() == len(STATIONS)


def test_advance_fills_every_elapsed_hour(fresh_db):
    sim.advance(fresh_db, now=NOW)
    result = sim.advance(fresh_db, now=NOW + timedelta(hours=5))
    assert result["hours"] == 5
    assert result["ridership"] == 5 * len(STATIONS)
    # One record per station per hour, with no gaps.
    assert fresh_db.query(ridership.RidershipRecord).count() == 6 * len(STATIONS)


def test_advance_is_idempotent_across_repeated_ticks(fresh_db):
    sim.advance(fresh_db, now=NOW)
    sim.advance(fresh_db, now=NOW + timedelta(hours=3))
    before = fresh_db.query(ridership.RidershipRecord).count()
    for _ in range(3):
        sim.advance(fresh_db, now=NOW + timedelta(hours=3))
    assert fresh_db.query(ridership.RidershipRecord).count() == before


def test_advance_does_not_rewind_when_database_is_ahead(fresh_db):
    sim.advance(fresh_db, now=NOW + timedelta(hours=10))
    before = fresh_db.query(ridership.RidershipRecord).count()
    result = sim.advance(fresh_db, now=NOW)
    assert result["hours"] == 0
    assert fresh_db.query(ridership.RidershipRecord).count() == before


def test_advance_extends_the_timetable_past_the_seed_lookahead(fresh_db):
    sim.advance(fresh_db, now=NOW)
    far = NOW + timedelta(hours=30)
    result = sim.advance(fresh_db, now=far)
    assert result["schedules"] > 0
    newest = fresh_db.query(schedule.TrainSchedule.arrival).order_by(
        schedule.TrainSchedule.arrival.desc()
    ).first()
    assert newest[0] >= far


def test_advance_caps_a_long_outage_backfill(fresh_db):
    sim.advance(fresh_db, now=NOW)
    result = sim.advance(fresh_db, now=NOW + timedelta(days=90))
    # Bounded by the retention window rather than replaying 90 days.
    assert result["hours"] <= sim.MAX_BACKFILL_HOURS
    assert fresh_db.query(ridership.RidershipRecord).count() <= (
        (sim.MAX_BACKFILL_HOURS + 1) * len(STATIONS)
    )


def test_prune_drops_rows_outside_the_retention_window(fresh_db):
    sim.advance(fresh_db, now=NOW)
    assert sim.prune(fresh_db, NOW) == 0
    later = NOW + timedelta(days=sim.HISTORY_DAYS + 1)
    # Prune clears both ridership and timetable rows.
    assert sim.prune(fresh_db, later) > 0
    assert fresh_db.query(ridership.RidershipRecord).count() == 0
    assert fresh_db.query(schedule.TrainSchedule).count() == 0


def test_prune_keeps_the_full_window_when_advanced_exactly(fresh_db):
    sim.advance(fresh_db, now=NOW)
    # Advancing to the retention boundary must not delete anything.
    assert sim.prune(fresh_db, NOW + timedelta(days=sim.HISTORY_DAYS)) == 0
    assert fresh_db.query(ridership.RidershipRecord).count() == len(STATIONS)


def test_advance_with_no_stations_does_nothing(fresh_db):
    for s in fresh_db.query(station.Station).all():
        fresh_db.delete(s)
    fresh_db.commit()
    assert sim.advance(fresh_db, now=NOW) == {
        "hours": 0, "ridership": 0, "schedules": 0, "pruned": 0,
    }


def test_station_index_order_follows_stations_csv(fresh_db):
    order = sim._station_order(fresh_db)
    codes = [c for c, _ in order]
    csv_codes = [c for c, _ in sim.csv_station_order()]
    assert [c for c in codes if c in csv_codes] == [c for c in csv_codes if c in codes]


def test_latest_covered_hour_tracks_the_newest_bucket(fresh_db):
    assert sim.latest_covered_hour(fresh_db) is None
    sim.advance(fresh_db, now=NOW)
    assert sim.latest_covered_hour(fresh_db) == NOW
