import csv
import logging
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

CONNECTIONS_FILE = Path(__file__).resolve().parents[2] / "data" / "connections.csv"

VALID_KINDS = ("along_line", "transfer")


@lru_cache(maxsize=1)
def load_connections() -> list[dict]:
    """Load the station-to-station graph generated by scripts/build_connections.py.

    Edges are real rail neighbours (``along_line``, with the routes that run the
    segment in ``vias``) or pedestrian interchanges (``transfer``), derived from
    the MTA GTFS feed plus documented corrections for same-complex transfers.
    """
    if not CONNECTIONS_FILE.exists():
        logger.warning("connections.csv not found at %s; serving an empty graph", CONNECTIONS_FILE)
        return []

    with CONNECTIONS_FILE.open(newline="", encoding="utf-8") as fh:
        rows = [
            {
                "from_code": row["from_code"].strip(),
                "to_code": row["to_code"].strip(),
                "kind": row["kind"].strip(),
                "vias": row.get("vias", "").strip() or "transfer",
            }
            for row in csv.DictReader(fh)
        ]

    bad = [r for r in rows if r["kind"] not in VALID_KINDS]
    if bad:
        logger.error("dropping %d invalid connection kinds: %s", len(bad), bad[:3])

    duplicates = []
    seen = set()
    for r in rows:
        key = frozenset((r["from_code"], r["to_code"]))
        if key in seen:
            duplicates.append(key)
        seen.add(key)

    return [r for r in rows if r["kind"] in VALID_KINDS]